language: csharp

script:
  - cp Src/.nuget/mono_support/Microsoft.Build.dll Src/.nuget/Microsoft.Build.dll
  - export EnableNuGetPackageRestore="true"
  - export MONO_IOMAP=all
  - mozroots --import --sync
  - mono Src/.nuget/NuGet.exe install Rosalia -ExcludeVersion -Prerelease
  - mono Src/.nuget/NuGet.exe restore "Src/Quantum.Build/packages.config" -OutputDirectory "Src/packages"
  - mono Rosalia/tools/Rosalia.exe "../../../Quantum.Build/Quantum.Build.csproj"
